server:
  port: 8888



encrypt:
  failOnError: true
  keyStore:
    location: file:///D://microservices//workspace//configServer//keys//configServer.jks
    password: 12345678
    secret: mykeypass
    alias: defaultkey